### ISSUE TITLE
密码问题

### ISSUE THREAD

**Issue by onedayherocoming** [baetyl/baetyl-docs-cn#76]
“然后用浏览器打开 http://127.0.0.1:8080/index.php ， 服务器输入：mariadb，账号输入：root，密码输入：secretpassword”
这里的密码不是secretpassword，而是安装mariadb后，有一段提示信息，使用指令
kubectl get secret --namespace default mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode
获取的密码

**Comment by hannatao** [comment]
文档已更新，由于数据库chart更新变化快，因此后续由于不提供数据库快速安装指南。
